# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/438b16b3-fece-4bb4-a14b-2809f3ad2c37";
      fsType = "ext4";
      options = [ "discard" ];
#      options = [ "discard" "noatime" "nodiratime" ];
    };

  boot.initrd.luks.devices = [{
    name = "crypto_root";
    device = "/dev/disk/by-uuid/4c7c188c-f0dc-437a-b324-9855f361c5b0";
    allowDiscards = true;
  }];


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/b368ecaf-8fe3-4f6b-bafe-cf916941a835";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
